s21-7pm-4 kk - added logo that is visible on every page
ucsb-cs156-s21/proj-mapache-search pull request #243
Opened 2021-05-12 20:17 UTC by karankhangura

The user will be able to see a logo in the navbar on every page.

2021-05-12 20:24 UTC, Vanessa-Salgado submitted a review, later dismissed
LGTM!

2021-05-12 20:29 UTC, nicomwong requested changes
LGTM except one change needed

2021-05-12 20:29 UTC, nicomwong commented on javascript/src/main/components/Nav/AppNavbar.js
> +          <p className="brand"><img className="brand" src={'https://user-images.githubusercontent.com/34492835/117874902-6d8fbc00-b256-11eb-8557-60c7b29b0809.png'}  alt="Mapache Search icon"  /></p>
Should the `src` be linked to a local file in the repo instead? Currently it is referencing a web URL.

2021-05-12 20:43 UTC, yuyuanwangshabi commented
LGTM

2021-05-12 20:43 UTC, nicomwong approved these changes
LGTM

2021-05-12 20:48 UTC, yuyuanwangshabi approved these changes
great

2021-05-12 22:05 UTC, Prothean051 approved these changes
LGTM, merge away

2021-05-12 22:08 UTC, merged

2021-05-13 08:39 UTC, andrewhlu reviewed
Please submit a new follow-up PR to address this change.

2021-05-13 08:39 UTC, andrewhlu commented on javascript/src/main/components/Nav/AppNavbar.js
> +          <p className="brand"><img className="brand" src={'navbarlogo.png'}  alt="Mapache Search icon"  /></p>
The logo only shows up on the main page, and does not show up on other pages. Please fix this such that it will show up on every page.