7pm-1 eo - Add page for links from each channel
ucsb-cs156-s21/proj-mapache-search pull request #258
Opened 2021-05-21 21:42 UTC by emilyomahony

In this PR we add a new page to display the links for each Slack channel, reachable from each channel's page. It can be found at /member/channels/{channel}/links. The original issue asked for the table of links to include links to the original message, but it is not feasible at this time to get that information, so the table just includes the user, the link, and the timestamp.

2021-05-23 19:50 UTC, stevendee37 submitted a review, later dismissed
Tested locally on device. Links from channel were displayed and clickable, leading to the correct websites. LGTM!

2021-05-26 02:43 UTC, andrewhlu requested changes

2021-05-26 02:43 UTC, andrewhlu commented on javascript/src/main/components/ChannelMessages/ChannelLinks.js
> +    var new_message;
Can we use `let` or `const` instead of `var`? It's better practice and it solves issues with scoping.

2021-05-26 02:43 UTC, andrewhlu commented on javascript/src/main/components/ChannelMessages/ChannelLinks.js
> +                var links = current.split('|');
same as above

2021-05-26 02:43 UTC, andrewhlu commented on javascript/src/main/pages/Channels/ChannelPageLinks.js
> +import { useParams} from "react-router-dom";
```suggestion
import { useParams } from "react-router-dom";
```

2021-05-26 02:43 UTC, andrewhlu commented on javascript/src/test/components/ChannelMessages/ChannelLinks.test.js
> +            "text": "Office hours at <https://ucsb.zoom.us/j/89220034995?pwd=VTlHNXJpTVgrSEs5QUtlMDdqMC9wQT09>",
Can we remove the class Zoom link and replace it with a placeholder value? This shouldn't be published.

2021-05-26 02:43 UTC, andrewhlu commented on javascript/src/test/components/ChannelMessages/ChannelLinks.test.js
> +        expect(linkElement.href).toEqual("https://ucsb.zoom.us/j/89220034995?pwd=VTlHNXJpTVgrSEs5QUtlMDdqMC9wQT09");
same as above

2021-05-26 02:43 UTC, andrewhlu commented on javascript/src/test/components/ChannelMessages/ChannelLinks.test.js
> +        expect(linkElement.href).toEqual("https://ucsb.zoom.us/j/89220034995?pwd=VTlHNXJpTVgrSEs5QUtlMDdqMC9wQT09");
same as above

2021-05-26 02:43 UTC, andrewhlu commented on javascript/src/test/pages/Channels/ChannelPage.test.js
> +        expect(contentsElement.href).toEqual("https://ucsb.zoom.us/j/89220034995?pwd=VTlHNXJpTVgrSEs5QUtlMDdqMC9wQT09");
same as above

2021-05-26 03:13 UTC, emilyomahony commented
All constructive feedback has been addressed; "var" has been replaced with "let" everywhere and the class zoom links have been replaced by placeholders.

2021-05-26 23:21 UTC, andrewhlu requested changes

2021-05-26 23:21 UTC, andrewhlu commented on javascript/src/test/components/ChannelMessages/ChannelLinks.test.js
> +            "text": "Office hours at <https://youtu.be/dQw4w9WgXcQ>",
i hate this so much

2021-05-26 23:21 UTC, andrewhlu commented on javascript/src/test/pages/Channels/ChannelPage.test.js
> +        expect(contentsElement.href).toEqual("https://ucsb.zoom.us/j/89220034995?pwd=VTlHNXJpTVgrSEs5QUtlMDdqMC9wQT09");
Looks like this one didn't get resolved, can you take a look again?

2021-05-27 00:15 UTC, andrewhlu submitted a review, later dismissed
🎵 Never gonna give you up 🎵
🎵 Never gonna let you down 🎵
🎵 Never gonna run around and desert you 🎵

2021-05-27 00:24 UTC, pconrad commented on javascript/src/test/components/ChannelMessages/ChannelLinks.test.js
> +            "text": "Office hours at <https://youtu.be/dQw4w9WgXcQ>",
Everyone loves Rick Astley

2021-05-27 22:14 UTC, ReileyB approved these changes
LGTM. tested on Heroku

2021-05-27 22:57 UTC, ReileyB submitted a review, later dismissed
LGTM

2021-05-28 10:16 UTC, andrewhlu requested changes
Hmm I'm noticing now that the page for channel links includes messages with user mentions, which I don't think should be counted as links for the purpose of this page. Could you fix this?

![image](https://user-images.githubusercontent.com/34492835/119969120-0581eb00-bf63-11eb-80cb-852bc57afd0a.png)

2021-05-28 21:08 UTC, emilyomahony commented
taking a look now, should able to address this on this PR rather than making a new one

2021-05-28 23:20 UTC, skiteskopes commented
LGTM!

2021-05-29 08:20 UTC, andrewhlu commented
> LGTM!

@skiteskopes This was made as a comment and not a formal approval. If you meant to give a full approval, please do so.

2021-05-29 08:27 UTC, andrewhlu approved these changes
LGTM, thanks for making all of these changes!

2021-05-29 15:58 UTC, ReileyB approved these changes
LGTM!

2021-05-29 20:36 UTC, merged