Working on problem #217 Show search quota before making first search …
ucsb-cs156-s21/proj-mapache-search pull request #274
Opened 2021-05-26 02:10 UTC by bowenduanmu

Show user search quota before the first search in Google Search page of the app.

2021-05-26 21:15 UTC, pconrad commented
Note: there is a missed line of coverage on the codecov patch... it says that line 62 is not covered by tests.

THAT IS OK.  We are going to let that slide.   Getting to the tests passing at all was hard fought, and it's getting late in the quarter.

2021-05-26 21:15 UTC, pconrad approved these changes
LGTM

2021-05-26 21:15 UTC, pconrad commented on javascript/src/main/pages/Search/Search.js
> +        };
This line not being covered by tests?  We are going to let that slide!!!  Sincerely, Prof. Conrad. Kthxbye.

2021-05-27 00:21 UTC, pconrad requested changes
There are a couple of console.log statements that we should remove.

After that, it looks good to me!

2021-05-27 00:21 UTC, pconrad commented on javascript/src/test/pages/Search/Search.test.js
> +                console.log(`url=${url}`)
Please remove this console.log

2021-05-27 00:21 UTC, pconrad commented on javascript/src/test/pages/Search/Search.test.js
> +                console.log(`url=${url}`)
Please remove this console.log

2021-05-27 00:21 UTC, pconrad commented on javascript/src/main/pages/Search/Search.js
> +            console.log("quotaInfo=",quotaInfo)
Please remove this console.log

2021-05-27 00:21 UTC, pconrad commented on javascript/src/main/pages/Search/Search.js
>              console.log(`err=${err}`);
This console.log is ok and can stay, since it is covering an error condition.

2021-05-27 00:39 UTC, ujcookcao approved these changes
The code successfully shows the quota in the google search function and passes all the tests.

2021-05-27 18:51 UTC, pconrad approved these changes
LGTM

2021-05-28 00:04 UTC, ujcookcao approved these changes
The code successfully shows the quota in the google search function and passes all the tests.

2021-05-28 10:30 UTC, andrewhlu commented
@pconrad I see that you previously said you were okay with overriding test coverage drops. If that's the case, feel free to merge.

2021-05-29 01:48 UTC, merged