Import from slack
ucsb-cs156-s21/proj-mapache-search pull request #284
Opened 2021-05-26 23:55 UTC by pconrad

In this PR, we add the code that has been used to upload a Slack archive to the MongoDB database.  This code had been maintained in a separate repo up until now, but should rightly be maintained as part of the project.

You will find:
* A `python` subdirectory for python code related to the project.
* In that subdirectory, an `importFromSlack` subdirectory with its own `README.md`, and `.gitignore`.
* A `requirements.txt` file that can be used with the `pip` utility to install Python dependencies
* A python script that can be used to upload a Slack archive.

The `README.md` contains instructions for using the script.

2021-05-26 23:59 UTC, andrewhlu requested changes

2021-05-26 23:59 UTC, andrewhlu commented on python/importFromSlack/README.md
> +This directory a python script to help upload slack archives to MongoDB.
```suggestion
This directory contains a python script to help upload slack archives to MongoDB.
```

2021-05-27 19:08 UTC, andrewhlu approved these changes

2021-05-28 04:13 UTC, JacquelineMai approved these changes

2021-05-28 04:14 UTC, merged