sk - Clean up 'search messages by user' page
ucsb-cs156-s21/proj-mapache-search pull request #294
Opened 2021-05-28 07:12 UTC by sarahkwon

In this pr, we made links, emails, and phone numbers clickable. We also show the user's real name when @'ed instead of their ID. Was not able to test or work on the duplicate messages issue due to a problem with the database, but the table displays the correct number of messages based on what was given in the database.

2021-05-28 20:03 UTC, stevendee37 requested changes

2021-05-28 20:03 UTC, stevendee37 commented on javascript/src/main/components/UserMessages/UserMessageList.js
> +    var bracketRegEx = /<(.*?)>/g;
Replace instances of "var" with "let." Helps with scope issues according to LAs.

2021-05-28 22:42 UTC, stevendee37 approved these changes

2021-05-28 22:44 UTC, stevendee37 approved these changes
LGTM! var replaced with let in appropriate places, and runs locally.

2021-05-29 20:46 UTC, mara-downing approved these changes
LGTM

2021-05-29 20:50 UTC, merged