7pm-2-ViewSearchesAsAdmin
ucsb-cs156-s21/proj-mapache-search pull request #306
Opened 2021-05-30 16:06 UTC by bowenduanmu

Maintain the page to show table for searches data in SearchHistory page and modify the SearchHistory controller for admin user.

2021-06-01 22:14 UTC, pconrad requested changes
It is really confusing that there are three open PRs, #305, #306, and #307 all seeming to be covering the same territory, in various stages of completion. 

Going through each of these separately wastes the time of the team and the staff, and time is running out.  

Please figure out which of these is the "real" one, and close the other two.  Or if they are really are focussed on different issues, make that more clear.

And the ones that aren't ready for review yet (e.g. have large sections of commented out code still to be written, mark them as drafts. )

2021-06-01 22:14 UTC, pconrad commented on javascript/src/main/App.js
>            <AuthorizedRoute path="/member/channels/:channel" component={ChannelPageScrollable} authorizedRoles={["admin","member"]} />
Still don't know why you are removing this line.     See Reviews on #305 and #307

2021-06-01 22:14 UTC, pconrad commented on src/main/java/edu/ucsb/mapache/controllers/SearchHistoryController.java
> +        String body=null;
Lines 66, 68-69 and 71 should be covered by tests.

2021-06-01 22:14 UTC, pconrad commented on src/test/java/edu/ucsb/mapache/controllers/SearchHistoryControllerTests.java
> +  public void test_getSearches_case2() throws Exception {
I am really confused why there are three different PRs that seem to be covering the same territory, and why there is commented out code still in two of them. 

Should these be closed or marked as drafts?

2021-06-02 06:52 UTC, closed without merging

2021-06-02 06:53 UTC, bowenduanmu commented
This PR is included in another PR.