7pm-2-MiniEpic-SearchHistory
ucsb-cs156-s21/proj-mapache-search pull request #307
Opened 2021-05-30 16:30 UTC by bowenduanmu

Combine the results of three substories and modified SearchHistory controller for different situation of admin users and member users. Check the function of page to correctly show the searches result table.

2021-06-01 22:07 UTC, pconrad requested changes
This seems to be incomplete.

2021-06-01 22:07 UTC, pconrad commented on src/main/java/edu/ucsb/mapache/controllers/SearchHistoryController.java
> +            String userid = firstName.concat(lastName);
These lines should be covered by tests.

2021-06-01 22:07 UTC, pconrad commented on src/test/java/edu/ucsb/mapache/controllers/SearchHistoryControllerTests.java
> +  // Look in other controller tests for examples
This code is NOT in final form to merge.   This is still essentially a draft PR.

Please let us know when it is ready to merge.  Code that's ready to merge doesn't have big blocks of commented out code in it.  This is code that I wrote to help your team... and you haven't done anything with it yet, at least not in this branch.

2021-06-01 22:07 UTC, pconrad commented on javascript/src/main/App.js
> -          <AuthorizedRoute path="/member/channels/:channel/links" component={ChannelPageLinks} authorizedRoles={["admin","member"]} />
Why did you remove this route that appears to have nothing to do with your PR?

You should put it back unless you have an explanation for why you are removing it.

2021-06-02 06:53 UTC, bowenduanmu commented
This PR is included in another PR.

2021-06-02 06:53 UTC, closed without merging